### ISSUE TITLE
The drush command 'cron' could not be executed.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#8] opened 2016-01-01 16:36 UTC
Running the command `drush cron` fails.

output:

```
geoff@gspmbp backdrop-drush-master (master) $ drush cron
Command core-cron needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this      [error]
command.
The drush command 'cron' could not be executed.
```

**Comment by quicksketch** [comment] 2016-01-22 07:06
Looks like this is because you weren't in a Drupal/Backdrop directory at the time. From the looks of it you were in the `backdrop-drush-master` directory. So this error is correct. Reopen if I've misunderstood.

**Comment by serundeputy** [comment] 2016-01-23 20:36
Yeah; I think you are right about the above post, but I think I copied the wrong thing; here is an attempt from inside a backdrop root:

```
geoff@gspmbp backdrop (1.x) $ pwd
/Users/geoff/sites/backdrop
geoff@gspmbp backdrop (1.x) $ ls
1196.patch      core            layouts         profiles        settings.php
1203.patch      files           local.gitignore     robots.txt      sites
README.md       index.php       modules         settings.local.php  themes
geoff@gspmbp backdrop (1.x) $ backdrop cron
PHP Fatal error:  Class 'Drupal\Core\Logger\RfcLogLevel' not found in /Users/geoff/brush/commands/core/drupal/environment.inc on line 334

Fatal error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in /Users/geoff/brush/commands/core/drupal/environment.inc on line 334
Drush command terminated abnormally due to an unrecoverable error.                                                                               [error]
Error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in /Users/geoff/brush/commands/core/drupal/environment.inc, line 334
geoff@gspmbp backdrop (1.x) $
```

one difference is that I have my drush instance installed in `root/of/drush/instance/commands` folder whereas I believe yours is in `~/.drush/commands` folder ... maybe that makes a difference?

**Comment by serundeputy** [comment] 2016-01-23 23:25
If I basically remove the whole function: `drush_watchdog_severity_levels` from environment.inc I can get cron to run and log as have been run in `/admin/reports/dblog`

``` php
function drush_watchdog_severity_levels() {
  return array(
    // RfcLogLevel::EMERGENCY => LogLevel::EMERGENCY,
    // RfcLogLevel::ALERT => LogLevel::ALERT,
    // RfcLogLevel::CRITICAL => LogLevel::CRITICAL,
    // RfcLogLevel::ERROR => LogLevel::ERROR,
    // RfcLogLevel::WARNING => LogLevel::WARNING,
    // RfcLogLevel::NOTICE => LogLevel::NOTICE,
    // RfcLogLevel::INFO => LogLevel::INFO,
    // RfcLogLevel::DEBUG => LogLevel::DEBUG,
  );
}
```

That obviously does not seem like a solution, but it is more information on the problem.

**Comment by quicksketch** [comment] 2016-01-26 05:41
Thanks for reopening. I'm running the latest 8.0.x branch, so perhaps this has been fixed over in Drush? It's odd to me that having the Backdrop extension would break the integration with Drupal 7. So if you remove the Backdrop extension, Drush 8 starts working with Drupal 7 again? Is it possible your version of Drush just isn't working with Drupal 7 at all?

**Comment by jenlampton** [comment] 2016-02-02 00:22
I'm on the latest drush 8 too and I get:
```
Fatal error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in /Users/jlampton/drush-8/commands/core/drupal/environment.inc on line 322
Drush command terminated abnormally due to an unrecoverable error.                                                     [error]
Error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in
/Users/jlampton/drush-8/commands/core/drupal/environment.inc, line 322
```

**Comment by jenlampton** [comment] 2016-03-13 23:55
I just upgraded to the lastest stable version of drush 8 - `drush 8.0.5` and this is the error and stack trace I get when running `drush cron`. My backdrop-drush commands are located in `~/.drush/commands` like @serundeputy. 

```
PHP Fatal error:  Class 'Drupal\Core\Logger\RfcLogLevel' not found in phar:///drush-8/drush/commands/core/drupal/environment.inc on line 334
PHP Stack trace:
PHP   1. _backdrop_exception_handler() backdrop/core/includes/bootstrap.inc:0
PHP   2. _backdrop_log_error() backdrop/core/includes/bootstrap.inc:2697
PHP   3. watchdog() backdrop/core/includes/errors.inc:208
PHP   4. module_invoke() backdrop/core/includes/bootstrap.inc:2078
PHP   5. call_user_func_array:{backdrop/core/includes/module.inc:913}() backdrop/core/includes/module.inc:913
PHP   6. system_watchdog() backdrop/core/includes/module.inc:913
PHP   7. drush_watchdog_severity_levels() phar:///drush-8/drush/includes/drupal.inc:86

Fatal error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in phar:///drush-8/drush/commands/core/drupal/environment.inc on line 334

Call Stack:
    0.7278    9701080   1. _backdrop_exception_handler() backdrop/core/includes/bootstrap.inc:0
    0.7282    9759280   2. _backdrop_log_error() backdrop/core/includes/bootstrap.inc:2697
    0.7507   12891608   3. watchdog() backdrop/core/includes/errors.inc:208
    0.7508   12894960   4. module_invoke() backdrop/core/includes/bootstrap.inc:2078
    0.7508   12896720   5. call_user_func_array:{backdrop/core/includes/module.inc:913}() backdrop/core/includes/module.inc:913
    0.7508   12897168   6. system_watchdog() backdrop/core/includes/module.inc:913
    0.7520   12963768   7. drush_watchdog_severity_levels() phar:///drush-8/drush/includes/drupal.inc:86

Drush command terminated abnormally due to an unrecoverable error.                                                                                                          [error]
Error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in phar:///drush-8/drush/commands/core/drupal/environment.inc, line 334
```

**Comment by jenlampton** [comment] 2016-03-14 00:05
> Is it possible your version of Drush just isn't working with Drupal 7 at all?

Yes, this is my situation exactly. Drush 8.0.5 does not work with Drupal 7. Here is the error I get:

```
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in drupal_is_denied() (line 1921 of drupal/includes/bootstrap.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in _registry_check_code() (line 3198 of drupal/includes/bootstrap.inc).</p><hr />Drush command terminated abnormally due to an unrecoverable error.  
```

Update: If I do a `git clone` and `composer update` instead of installing with the .phar, things seem to work as expected. See related: https://github.com/drush-ops/drush/issues/657

**Comment by jenlampton** [comment] 2016-03-14 00:15
Now that Drush 8 is working with Drupal 7 without the Backdrop commands, I added the commands to test again. When I do a `drush cron` from within Drupal 7, I get the following error:

```
Fatal error: Call to undefined function drush_get_bootstrap_object() in ~/drush-8/commands/backdrop/backdrop.drush.inc on line 28
Drush command terminated abnormally due to an unrecoverable error.                                                                                                          [error]
Error: Call to undefined function drush_get_bootstrap_object() in ~/drush-8/commands/backdrop/backdrop.drush.inc, line 28
```

I think this is becoming a duplicate of https://github.com/backdrop-contrib/drush/issues/24

**Comment by jenlampton** [comment] 2016-03-14 00:17
I think this is becoming a duplicate of https://github.com/backdrop-contrib/drush/issues/9

**Comment by serundeputy** [comment] 2016-03-14 00:24
@jenlampton I think that the information you are seeing is dupe of #9, however I've never gotten the command:

``` php
drush cron
```

to work in my Backdrop sites. 

The best configuration I've found so far is a separate drush install and put the backdrop-drush/extension into `NEW_DRUSH_ROOT/commands/backdrop`

Having said that even with this configuration `drush cron` does not work for me.

**Comment by jenlampton** [comment] 2016-03-14 01:59
Now that I have my drush working again, I can confirm that `drush cron` is no longer working for me as well. 

```
Fatal error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in drush-8/commands/core/drupal/environment.inc on line 334
Drush command terminated abnormally due to an unrecoverable error.                                                                                                          [error]
Error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in drush-8/commands/core/drupal/environment.inc, line 334
```

**Comment by quicksketch** [comment] 2016-03-25 20:39
I ran into this error as well, as reported by Jen in the previous comment.

The problem here is that `drush cron` calls `backdrop_cron_run()`, which eventually runs this:

```
watchdog('cron', 'Cron run completed.', array(), WATCHDOG_NOTICE);
```

That in itself won't _normally_ cause a problem. But Drush has an implementation of `hook_watchdog()` in its own code: https://github.com/drush-ops/drush/blob/91d697e387be4955a48c49b2e8eb80e2a8007734/commands/runserver/runserver-prepend.php#L35

Drush's hook_watchdog() only works in Drupal 7 and 8, and it's what will try to call the `Drupal\Core\Logger\RfcLogLevel` class and cause the problem.

The reason why this wasn't happening all the time is because if the hook registry already was generated, Drush wouldn't have its hook_watchdog() called. If you cleared the cache from Drush however, the hook_watchdog() would be registered. So it was inconsistent as to whether or not the error was triggered.

We can fix this problem by using the same trick Drush used to inject hook_watchdog() to remove it: imitate system module, but use `hook_implements_alter()` to take it back out. Something like this:

``` php
/**
 * Implements hook_module_implements_alter().
 *
 * This is a hack to remove core Drush's implementation of hook_watchdog() from
 * the hook registry. See system_watchdog() in Drush core.
 */
function system_module_implements_alter(&$implementations, $hook) {
  // Remove system_watchdog() from being called.
  if ($hook === 'watchdog') {
    $implementations = array_diff_key($implementations, array('system' => NULL));
  }
}
```

**Comment by quicksketch** [comment] 2016-03-25 20:55
I pushed https://github.com/backdrop-contrib/drush/commit/d5bea1ff4e37c7fa2f50571e57f082e7a46c020f, which as far as I can tell resolves this problem.

Please reopen if it still seems to occur.

**Closed as completed by quicksketch** 2016-03-25 20:55 UTC

**Comment by quicksketch** [comment] 2016-03-25 21:57
Oops, I went a little overboard and broke the `drush cc` command. Restored in https://github.com/backdrop-contrib/drush/commit/73ffce61d7cc6b5354d18954f0bbf938a3768fd8.

**Comment by lynna-spidersilk** [comment] 2017-07-13 19:54
OK, apparently I can't reopen a closed issue - will move my comment to a new one.
